<?php
declare(strict_types=1);
namespace GymPro\Services;
use RuntimeException;
final class AttendanceService
{
 public static function checkIn(int $memberId,int $actorId): int
 {return \transaction(function()use($memberId,$actorId){$member=\db_one("SELECT m.Name,p.AllowsGymAccess FROM MEMBER m JOIN SUBSCRIPTION s ON s.MemberID=m.MemberID AND s.Status='ACTIVE' AND s.StartsAt<=NOW() AND s.EndsAt>=NOW() JOIN MEMBERSHIP_PLAN p ON p.PlanID=s.PlanID JOIN USER_ACCOUNT u ON u.MemberID=m.MemberID AND u.Status='ACTIVE' WHERE m.MemberID=? FOR UPDATE",'i',[$memberId]);if(!$member||!$member['AllowsGymAccess'])throw new RuntimeException('Member does not have active gym access.');if(\db_one("SELECT GymAttendanceID FROM GYM_ATTENDANCE WHERE MemberID=? AND Status='CHECKED_IN' AND CheckOutAt IS NULL",'i',[$memberId]))throw new RuntimeException('Member is already checked in.');\db_execute("INSERT INTO GYM_ATTENDANCE (MemberID,CheckInAt,CheckedInBy) VALUES (?,NOW(),?)",'ii',[$memberId,$actorId]);$id=\db()->insert_id;\audit('gym.check_in','GYM_ATTENDANCE',$id,['member_id'=>$memberId]);return $id;});}
 public static function checkOut(int $visitId,int $actorId): void
 {\transaction(function()use($visitId,$actorId){$v=\db_one("SELECT * FROM GYM_ATTENDANCE WHERE GymAttendanceID=? AND Status='CHECKED_IN' AND CheckOutAt IS NULL FOR UPDATE",'i',[$visitId]);if(!$v)throw new RuntimeException('Open gym visit not found.');\db_execute("UPDATE GYM_ATTENDANCE SET CheckOutAt=NOW(),CheckedOutBy=?,Status='CHECKED_OUT' WHERE GymAttendanceID=?",'ii',[$actorId,$visitId]);\audit('gym.check_out','GYM_ATTENDANCE',$visitId,['member_id'=>$v['MemberID']]);});}
 public static function markClass(int $sessionId,int $trainerId,array $statuses): void
 {\transaction(function()use($sessionId,$trainerId,$statuses){$session=\db_one('SELECT s.*,c.TrainerID FROM CLASS_SESSION s JOIN CLASS c ON c.ClassID=s.ClassID WHERE s.SessionID=? FOR UPDATE','i',[$sessionId]);if(!$session||(int)$session['TrainerID']!==$trainerId)throw new RuntimeException('Class session is unavailable.');foreach($statuses as $eid=>$status){$eid=(int)$eid;if(!in_array($status,['PRESENT','ABSENT','LATE','EXCUSED'],true))continue;$valid=\db_one("SELECT e.EnrollmentID FROM ENROLLMENT e JOIN CLASS c ON c.ClassID=e.ClassID WHERE e.EnrollmentID=? AND e.ClassID=? AND e.Status='ENROLLED' AND c.TrainerID=?",'iii',[$eid,$session['ClassID'],$trainerId]);if(!$valid)throw new RuntimeException('Invalid class roster entry.');\db_execute("INSERT INTO CLASS_ATTENDANCE (SessionID,EnrollmentID,Status,MarkedBy) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE Status=VALUES(Status),MarkedBy=VALUES(MarkedBy),MarkedAt=NOW()",'iisi',[$sessionId,$eid,$status,\current_user()['UserID']]);}\audit('class.attendance_marked','CLASS_SESSION',$sessionId,['records'=>count($statuses)]);});}
}
