<?php
declare(strict_types=1);
namespace GymPro\Services;
use RuntimeException;
final class CommissionService
{
 public static function completeSession(int $sessionId,int $trainerId): void
 {\transaction(function()use($sessionId,$trainerId){$s=\db_one("SELECT s.*,c.TrainerID,c.RatePerClass FROM CLASS_SESSION s JOIN CLASS c ON c.ClassID=s.ClassID WHERE s.SessionID=? FOR UPDATE",'i',[$sessionId]);if(!$s||(int)$s['TrainerID']!==$trainerId)throw new RuntimeException('Session not found.');if($s['Status']==='COMPLETED')return;$rule=\db_one("SELECT * FROM COMMISSION_RULE WHERE IsActive=1 AND EffectiveFrom<=CURDATE() AND (EffectiveTo IS NULL OR EffectiveTo>=CURDATE()) ORDER BY EffectiveFrom DESC LIMIT 1");if(!$rule)throw new RuntimeException('No active commission rule exists.');$basis=(float)$s['RatePerClass'];$amount=$rule['CalculationType']==='PERCENTAGE'?round($basis*(float)$rule['Rate']/100,2):(float)$rule['Rate'];\db_execute("UPDATE CLASS_SESSION SET Status='COMPLETED',CompletedAt=NOW() WHERE SessionID=?",'i',[$sessionId]);\db_execute("UPDATE CLASS SET Status='COMPLETED' WHERE ClassID=?",'i',[$s['ClassID']]);\db_execute("INSERT IGNORE INTO COMMISSION_ENTRY (TrainerID,SessionID,RuleID,CalculationType,RateSnapshot,BasisAmount,Amount,Status,EarnedAt) VALUES (?,?,?,?,?,?,?,'EARNED',NOW())",'iiisddd',[$trainerId,$sessionId,$rule['RuleID'],$rule['CalculationType'],$rule['Rate'],$basis,$amount]);\audit('class.completed','CLASS_SESSION',$sessionId,['commission'=>$amount]);});}
 public static function payout(int $trainerId,int $actorId): int
 {return \transaction(function()use($trainerId,$actorId){$entries=\db_all("SELECT * FROM COMMISSION_ENTRY WHERE TrainerID=? AND Status='EARNED' FOR UPDATE",'i',[$trainerId]);if(!$entries)throw new RuntimeException('No earned commission is awaiting payout.');$amount=array_sum(array_map(fn($e)=>(float)$e['Amount'],$entries));$ref='PAY-'.strtoupper(bin2hex(random_bytes(7)));\db_execute("INSERT INTO PAYOUT (TrainerID,Amount,Status,Reference,PaidAt,CreatedBy) VALUES (?,?,'PAID',?,NOW(),?)",'idsi',[$trainerId,$amount,$ref,$actorId]);$pid=\db()->insert_id;foreach($entries as $e){\db_execute('INSERT INTO PAYOUT_ITEM (PayoutID,CommissionEntryID,Amount) VALUES (?,?,?)','iid',[$pid,$e['CommissionEntryID'],$e['Amount']]);\db_execute("UPDATE COMMISSION_ENTRY SET Status='PAID' WHERE CommissionEntryID=?",'i',[$e['CommissionEntryID']]);}\audit('commission.paid','PAYOUT',$pid,['amount'=>$amount,'reference'=>$ref]);return $pid;});}
}
