<?php
declare(strict_types=1);
require_once __DIR__ . '/../bootstrap/app.php';
use GymPro\V2\Services\AttendanceService;
require_role('RECEPTIONIST');$actorId=(int)current_user()['UserAccountID'];$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$action=(string)($_POST['action']??'');if($action==='check_in'){AttendanceService::checkIn($actorId,(int)($_POST['member_id']??0));flash('success','Member checked in successfully.');}elseif($action==='check_out'){AttendanceService::checkOut($actorId,(int)($_POST['visit_id']??0));flash('success','Member checked out successfully.');}else{throw new InvalidArgumentException('Choose a valid reception action.');}redirect('reception/index.php');}catch(Throwable $exception){$error=$exception->getMessage();}}
$q=trim((string)($_GET['q']??''));$members=$q===''?[]:db_all("SELECT m.MemberID,m.MemberNumber,CONCAT(m.FirstName,' ',m.LastName) Name,m.Status,ms.Status MembershipStatus,ms.EndsOn,(SELECT gv.GymVisitID FROM GYM_VISIT gv WHERE gv.MemberID=m.MemberID AND gv.CheckedOutAt IS NULL LIMIT 1) OpenVisit FROM MEMBER m LEFT JOIN MEMBERSHIP ms ON ms.MembershipID=(SELECT x.MembershipID FROM MEMBERSHIP x WHERE x.MemberID=m.MemberID ORDER BY x.MembershipID DESC LIMIT 1) WHERE m.MemberNumber LIKE CONCAT('%',?,'%') OR m.FirstName LIKE CONCAT('%',?,'%') OR m.LastName LIKE CONCAT('%',?,'%') LIMIT 25",'sss',[$q,$q,$q]);$inside=db_all("SELECT gv.GymVisitID,gv.CheckedInAt,m.MemberNumber,CONCAT(m.FirstName,' ',m.LastName) Name FROM GYM_VISIT gv JOIN MEMBER m ON m.MemberID=gv.MemberID WHERE gv.CheckedOutAt IS NULL ORDER BY gv.CheckedInAt DESC");
$pageTitle='Reception dashboard';$pageSubtitle='Member check-in and check-out';include V3_ROOT.'/includes/header.php';?>
<?php if($error!==''):?><div class="alert alert-danger" role="alert"><?=e($error)?></div><?php endif;?><form method="get" class="hero-search" role="search"><label for="member-search">Find a member<input id="member-search" name="q" value="<?=e($q)?>" placeholder="Member number or name" autocomplete="off"></label><button class="btn btn-primary" type="submit">Search</button></form><?php if($q!==''):?><div class="table-wrap"><table><caption class="sr-only">Member search results</caption><thead><tr><th>Member</th><th>Membership</th><th>Action</th></tr></thead><tbody><?php foreach($members as $member):?><tr><td><?=e($member['Name'])?><br><small><?=e($member['MemberNumber'])?></small></td><td><span class="status-badge status-<?=e(strtolower($member['MembershipStatus']??'none'))?>"><?=e(ucwords(strtolower($member['MembershipStatus']??'NONE')))?></span><?php if($member['EndsOn']):?> <small>to <?=e($member['EndsOn'])?></small><?php endif;?></td><td><form method="post"><?=csrf_field()?><?php if($member['OpenVisit']):?><input type="hidden" name="visit_id" value="<?=(int)$member['OpenVisit']?>"><button class="btn btn-secondary" type="submit" name="action" value="check_out">Check out</button><?php else:?><input type="hidden" name="member_id" value="<?=(int)$member['MemberID']?>"><button class="btn btn-primary" type="submit" name="action" value="check_in">Check in</button><?php endif;?></form></td></tr><?php endforeach;?><?php if(!$members):?><tr><td colspan="3">No matching members.</td></tr><?php endif;?></tbody></table></div><?php endif;?><section class="panel"><h2>Currently inside (<?=count($inside)?>)</h2><div class="table-wrap"><table><caption class="sr-only">Members currently inside the gym</caption><thead><tr><th>Member</th><th>Checked in</th><th>Action</th></tr></thead><tbody><?php foreach($inside as $visit):?><tr><td><?=e($visit['Name'])?><br><small><?=e($visit['MemberNumber'])?></small></td><td><?=e($visit['CheckedInAt'])?></td><td><form method="post"><?=csrf_field()?><input type="hidden" name="visit_id" value="<?=(int)$visit['GymVisitID']?>"><button class="btn btn-secondary" type="submit" name="action" value="check_out">Check out</button></form></td></tr><?php endforeach;?><?php if(!$inside):?><tr><td colspan="3">Nobody is currently checked in.</td></tr><?php endif;?></tbody></table></div></section><?php include V3_ROOT.'/includes/footer.php';?>
