CREATE TABLE IF NOT EXISTS SCHEMA_MIGRATION (
    MigrationID VARCHAR(100) PRIMARY KEY,
    AppliedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE MEMBERSHIP_PLAN
    ADD COLUMN IF NOT EXISTS IsActive TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS AllowsGymAccess TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS AllowsClasses TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ClassLimitPerCycle INT NULL,
    ADD COLUMN IF NOT EXISTS CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE MEMBER
    ADD COLUMN IF NOT EXISTS MemberNumber VARCHAR(24) NULL,
    ADD COLUMN IF NOT EXISTS CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS ArchivedAt DATETIME NULL;

UPDATE MEMBER SET MemberNumber=CONCAT('MEM-',LPAD(MemberID,6,'0')) WHERE MemberNumber IS NULL;

ALTER TABLE TRAINER
    ADD COLUMN IF NOT EXISTS Bio TEXT NULL,
    ADD COLUMN IF NOT EXISTS Specialization VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS ApplicationStatus VARCHAR(30) NOT NULL DEFAULT 'LEGACY_APPROVED',
    ADD COLUMN IF NOT EXISTS RejectionReason VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS ArchivedAt DATETIME NULL;

ALTER TABLE CLASS
    ADD COLUMN IF NOT EXISTS Status VARCHAR(30) NOT NULL DEFAULT 'SCHEDULED',
    ADD COLUMN IF NOT EXISTS ReviewNotes VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS ReviewedBy INT NULL,
    ADD COLUMN IF NOT EXISTS ReviewedAt DATETIME NULL,
    ADD COLUMN IF NOT EXISTS CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

UPDATE CLASS SET Capacity=10 WHERE Capacity > 10;

ALTER TABLE ENROLLMENT
    ADD COLUMN IF NOT EXISTS Status VARCHAR(30) NOT NULL DEFAULT 'ENROLLED',
    ADD COLUMN IF NOT EXISTS RequestedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS ReviewedAt DATETIME NULL,
    ADD COLUMN IF NOT EXISTS ReviewedBy INT NULL,
    ADD COLUMN IF NOT EXISTS CancellationEffectiveAt DATETIME NULL,
    ADD COLUMN IF NOT EXISTS DecisionReason VARCHAR(500) NULL,
    ADD UNIQUE KEY IF NOT EXISTS uq_member_class (MemberID,ClassID);

ALTER TABLE MEMBER ADD UNIQUE KEY IF NOT EXISTS uq_member_number (MemberNumber);

CREATE TABLE IF NOT EXISTS USER_ACCOUNT (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Email VARCHAR(190) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Role VARCHAR(20) NOT NULL,
    Status VARCHAR(30) NOT NULL DEFAULT 'PENDING_EMAIL',
    MemberID INT NULL UNIQUE,
    TrainerID INT NULL UNIQUE,
    EmailVerifiedAt DATETIME NULL,
    PaymentDueAt DATETIME NULL,
    LastLoginAt DATETIME NULL,
    FailedLoginCount INT NOT NULL DEFAULT 0,
    LockedUntil DATETIME NULL,
    RejectedAt DATETIME NULL,
    RejectionReason VARCHAR(500) NULL,
    ExpiredAt DATETIME NULL,
    AnonymizedAt DATETIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_member FOREIGN KEY (MemberID) REFERENCES MEMBER(MemberID) ON DELETE SET NULL,
    CONSTRAINT fk_user_trainer FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE SET NULL,
    INDEX idx_user_role_status (Role,Status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE CLASS
    ADD CONSTRAINT fk_class_reviewer FOREIGN KEY (ReviewedBy) REFERENCES USER_ACCOUNT(UserID) ON DELETE SET NULL;
ALTER TABLE ENROLLMENT
    ADD CONSTRAINT fk_enrollment_reviewer FOREIGN KEY (ReviewedBy) REFERENCES USER_ACCOUNT(UserID) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS EMAIL_VERIFICATION_TOKEN (
    TokenID BIGINT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    TokenHash CHAR(64) NOT NULL UNIQUE,
    ExpiresAt DATETIME NOT NULL,
    ConsumedAt DATETIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID) ON DELETE CASCADE,
    INDEX idx_email_token_user (UserID,ExpiresAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PASSWORD_RESET_TOKEN (
    TokenID BIGINT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    TokenHash CHAR(64) NOT NULL UNIQUE,
    ExpiresAt DATETIME NOT NULL,
    ConsumedAt DATETIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID) ON DELETE CASCADE,
    INDEX idx_reset_token_user (UserID,ExpiresAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TRAINER_DOCUMENT (
    DocumentID INT PRIMARY KEY AUTO_INCREMENT,
    TrainerID INT NOT NULL,
    StoredName VARCHAR(255) NOT NULL UNIQUE,
    OriginalName VARCHAR(255) NOT NULL,
    MimeType VARCHAR(100) NOT NULL,
    FileSize INT NOT NULL,
    Sha256 CHAR(64) NOT NULL,
    ReviewStatus VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    ReviewedBy INT NULL,
    ReviewedAt DATETIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE,
    FOREIGN KEY (ReviewedBy) REFERENCES USER_ACCOUNT(UserID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SUBSCRIPTION (
    SubscriptionID INT PRIMARY KEY AUTO_INCREMENT,
    MemberID INT NOT NULL,
    PlanID INT NOT NULL,
    PlanNameSnapshot VARCHAR(100) NOT NULL,
    PriceSnapshot DECIMAL(10,2) NOT NULL,
    DurationMonthsSnapshot INT NOT NULL,
    Status VARCHAR(30) NOT NULL DEFAULT 'PENDING_PAYMENT',
    PaymentDueAt DATETIME NULL,
    StartsAt DATETIME NULL,
    EndsAt DATETIME NULL,
    CancelAtPeriodEnd TINYINT(1) NOT NULL DEFAULT 0,
    Source VARCHAR(20) NOT NULL DEFAULT 'APPLICATION',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (MemberID) REFERENCES MEMBER(MemberID) ON DELETE RESTRICT,
    FOREIGN KEY (PlanID) REFERENCES MEMBERSHIP_PLAN(PlanID) ON DELETE RESTRICT,
    INDEX idx_subscription_member_status (MemberID,Status),
    INDEX idx_subscription_end (Status,EndsAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS MEMBERSHIP_PAYMENT (
    MembershipPaymentID BIGINT PRIMARY KEY AUTO_INCREMENT,
    SubscriptionID INT NOT NULL,
    MemberID INT NOT NULL,
    Amount DECIMAL(10,2) NOT NULL,
    Currency CHAR(3) NOT NULL DEFAULT 'LKR',
    Status VARCHAR(20) NOT NULL,
    Provider VARCHAR(30) NOT NULL DEFAULT 'SIMULATED_CARD',
    TransactionReference VARCHAR(64) NOT NULL UNIQUE,
    IdempotencyKey VARCHAR(64) NOT NULL UNIQUE,
    CardBrand VARCHAR(20) NULL,
    CardLast4 CHAR(4) NULL,
    Source VARCHAR(20) NOT NULL DEFAULT 'SIMULATION',
    PaidAt DATETIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SubscriptionID) REFERENCES SUBSCRIPTION(SubscriptionID) ON DELETE RESTRICT,
    FOREIGN KEY (MemberID) REFERENCES MEMBER(MemberID) ON DELETE RESTRICT,
    INDEX idx_member_payment (MemberID,Status,PaidAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CLASS_SESSION (
    SessionID INT PRIMARY KEY AUTO_INCREMENT,
    ClassID INT NOT NULL,
    StartsAt DATETIME NOT NULL,
    EndsAt DATETIME NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    CompletedAt DATETIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ClassID) REFERENCES CLASS(ClassID) ON DELETE CASCADE,
    UNIQUE KEY uq_class_session_start (ClassID,StartsAt),
    INDEX idx_session_status_start (Status,StartsAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GYM_ATTENDANCE (
    GymAttendanceID BIGINT PRIMARY KEY AUTO_INCREMENT,
    MemberID INT NOT NULL,
    CheckInAt DATETIME NOT NULL,
    CheckOutAt DATETIME NULL,
    CheckedInBy INT NOT NULL,
    CheckedOutBy INT NULL,
    Method VARCHAR(20) NOT NULL DEFAULT 'RECEPTION',
    Status VARCHAR(20) NOT NULL DEFAULT 'CHECKED_IN',
    IsOpen TINYINT GENERATED ALWAYS AS (CASE WHEN CheckOutAt IS NULL AND Status='CHECKED_IN' THEN 1 ELSE NULL END) STORED,
    CorrectionReason VARCHAR(500) NULL,
    IsEstimatedCheckout TINYINT(1) NOT NULL DEFAULT 0,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (MemberID) REFERENCES MEMBER(MemberID) ON DELETE RESTRICT,
    FOREIGN KEY (CheckedInBy) REFERENCES USER_ACCOUNT(UserID) ON DELETE RESTRICT,
    FOREIGN KEY (CheckedOutBy) REFERENCES USER_ACCOUNT(UserID) ON DELETE SET NULL,
    UNIQUE KEY uq_member_open_visit (MemberID,IsOpen),
    INDEX idx_gym_attendance_date (CheckInAt,Status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CLASS_ATTENDANCE (
    ClassAttendanceID BIGINT PRIMARY KEY AUTO_INCREMENT,
    SessionID INT NOT NULL,
    EnrollmentID INT NOT NULL,
    Status VARCHAR(20) NOT NULL,
    MarkedBy INT NOT NULL,
    MarkedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CorrectionReason VARCHAR(500) NULL,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (SessionID) REFERENCES CLASS_SESSION(SessionID) ON DELETE CASCADE,
    FOREIGN KEY (EnrollmentID) REFERENCES ENROLLMENT(EnrollmentID) ON DELETE RESTRICT,
    FOREIGN KEY (MarkedBy) REFERENCES USER_ACCOUNT(UserID) ON DELETE RESTRICT,
    UNIQUE KEY uq_session_enrollment (SessionID,EnrollmentID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS NOTIFICATION (
    NotificationID BIGINT PRIMARY KEY AUTO_INCREMENT,
    SenderUserID INT NULL,
    Title VARCHAR(150) NOT NULL,
    Body TEXT NOT NULL,
    Type VARCHAR(30) NOT NULL DEFAULT 'INFO',
    EntityType VARCHAR(50) NULL,
    EntityID INT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SenderUserID) REFERENCES USER_ACCOUNT(UserID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS NOTIFICATION_RECIPIENT (
    NotificationID BIGINT NOT NULL,
    UserID INT NOT NULL,
    ReadAt DATETIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (NotificationID,UserID),
    FOREIGN KEY (NotificationID) REFERENCES NOTIFICATION(NotificationID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID) ON DELETE CASCADE,
    INDEX idx_recipient_unread (UserID,ReadAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS COMMISSION_RULE (
    RuleID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    CalculationType VARCHAR(20) NOT NULL DEFAULT 'PERCENTAGE',
    Rate DECIMAL(10,4) NOT NULL,
    IsActive TINYINT(1) NOT NULL DEFAULT 1,
    EffectiveFrom DATE NOT NULL,
    EffectiveTo DATE NULL,
    CreatedBy INT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CreatedBy) REFERENCES USER_ACCOUNT(UserID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS COMMISSION_ENTRY (
    CommissionEntryID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TrainerID INT NOT NULL,
    SessionID INT NULL,
    RuleID INT NULL,
    CalculationType VARCHAR(20) NOT NULL,
    RateSnapshot DECIMAL(10,4) NOT NULL,
    BasisAmount DECIMAL(10,2) NOT NULL,
    Amount DECIMAL(10,2) NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'EARNED',
    ReversalOfID BIGINT NULL,
    EarnedAt DATETIME NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE RESTRICT,
    FOREIGN KEY (SessionID) REFERENCES CLASS_SESSION(SessionID) ON DELETE SET NULL,
    FOREIGN KEY (RuleID) REFERENCES COMMISSION_RULE(RuleID) ON DELETE SET NULL,
    FOREIGN KEY (ReversalOfID) REFERENCES COMMISSION_ENTRY(CommissionEntryID) ON DELETE RESTRICT,
    UNIQUE KEY uq_session_commission (SessionID),
    INDEX idx_commission_trainer_status (TrainerID,Status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PAYOUT (
    PayoutID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TrainerID INT NOT NULL,
    Amount DECIMAL(10,2) NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'PAID',
    Reference VARCHAR(64) NOT NULL UNIQUE,
    PaidAt DATETIME NOT NULL,
    CreatedBy INT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE RESTRICT,
    FOREIGN KEY (CreatedBy) REFERENCES USER_ACCOUNT(UserID) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PAYOUT_ITEM (
    PayoutID BIGINT NOT NULL,
    CommissionEntryID BIGINT NOT NULL UNIQUE,
    Amount DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (PayoutID,CommissionEntryID),
    FOREIGN KEY (PayoutID) REFERENCES PAYOUT(PayoutID) ON DELETE RESTRICT,
    FOREIGN KEY (CommissionEntryID) REFERENCES COMMISSION_ENTRY(CommissionEntryID) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    AuditID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ActorUserID INT NULL,
    Action VARCHAR(100) NOT NULL,
    EntityType VARCHAR(50) NOT NULL,
    EntityID INT NULL,
    Metadata JSON NULL,
    IPAddress VARCHAR(45) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ActorUserID) REFERENCES USER_ACCOUNT(UserID) ON DELETE SET NULL,
    INDEX idx_audit_entity (EntityType,EntityID),
    INDEX idx_audit_created (CreatedAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS JOB_RUN (
    JobKey VARCHAR(100) PRIMARY KEY,
    LastStartedAt DATETIME NULL,
    LastCompletedAt DATETIME NULL,
    LastStatus VARCHAR(20) NULL,
    LastMessage VARCHAR(500) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO COMMISSION_RULE (Name,CalculationType,Rate,EffectiveFrom)
VALUES ('Default class commission','PERCENTAGE',20.0000,CURDATE());

INSERT IGNORE INTO CLASS_SESSION (ClassID,StartsAt,EndsAt,Status)
SELECT ClassID, CONCAT(DateOfClass,' ',StartTime), CONCAT(DateOfClass,' ',EndTime),
       CASE WHEN CONCAT(DateOfClass,' ',EndTime) < NOW() THEN 'COMPLETED' ELSE 'SCHEDULED' END
FROM CLASS;

INSERT INTO SUBSCRIPTION (MemberID,PlanID,PlanNameSnapshot,PriceSnapshot,DurationMonthsSnapshot,Status,StartsAt,EndsAt,Source)
SELECT m.MemberID,p.PlanID,p.PlanName,p.Price,p.Duration,
       CASE WHEN m.PlanEndDate >= CURDATE() THEN 'ACTIVE' ELSE 'EXPIRED' END,
       CONCAT(m.PlanStartDate,' 00:00:00'), CONCAT(m.PlanEndDate,' 23:59:59'),'LEGACY'
FROM MEMBER m JOIN MEMBERSHIP_PLAN p ON p.PlanID=m.PlanID
WHERE m.PlanStartDate IS NOT NULL AND m.PlanEndDate IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM SUBSCRIPTION s WHERE s.MemberID=m.MemberID AND s.Source='LEGACY');
