CREATE TABLE IF NOT EXISTS CONVERSATION (
    ConversationID BIGINT PRIMARY KEY AUTO_INCREMENT,
    Channel VARCHAR(20) NOT NULL,
    MemberID INT NOT NULL,
    ClassID INT NULL,
    TrainerID INT NULL,
    Subject VARCHAR(150) NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    ContextKey VARCHAR(190) NOT NULL UNIQUE,
    LastMessageAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (MemberID) REFERENCES MEMBER(MemberID) ON DELETE RESTRICT,
    FOREIGN KEY (ClassID) REFERENCES CLASS(ClassID) ON DELETE RESTRICT,
    FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE RESTRICT,
    INDEX idx_conversation_member (MemberID,LastMessageAt),
    INDEX idx_conversation_trainer (TrainerID,LastMessageAt),
    INDEX idx_conversation_support (Channel,Status,LastMessageAt),
    CONSTRAINT chk_conversation_channel CHECK (
        (Channel='ADMIN_SUPPORT' AND ClassID IS NULL AND TrainerID IS NULL)
        OR (Channel='CLASS_TRAINER' AND ClassID IS NOT NULL AND TrainerID IS NOT NULL)
    ),
    CONSTRAINT chk_conversation_status CHECK (Status IN ('OPEN','CLOSED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CONVERSATION_MESSAGE (
    MessageID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ConversationID BIGINT NOT NULL,
    SenderUserID INT NOT NULL,
    Body TEXT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ConversationID) REFERENCES CONVERSATION(ConversationID) ON DELETE CASCADE,
    FOREIGN KEY (SenderUserID) REFERENCES USER_ACCOUNT(UserID) ON DELETE RESTRICT,
    INDEX idx_conversation_message (ConversationID,MessageID),
    INDEX idx_message_sender (SenderUserID,CreatedAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CONVERSATION_PARTICIPANT (
    ConversationID BIGINT NOT NULL,
    UserID INT NOT NULL,
    LastReadMessageID BIGINT NULL,
    ReadAt DATETIME NULL,
    JoinedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ConversationID,UserID),
    FOREIGN KEY (ConversationID) REFERENCES CONVERSATION(ConversationID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID) ON DELETE CASCADE,
    FOREIGN KEY (LastReadMessageID) REFERENCES CONVERSATION_MESSAGE(MessageID) ON DELETE SET NULL,
    INDEX idx_participant_unread (UserID,LastReadMessageID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
