<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}require_once __DIR__.'/../bootstrap/app.php';
$key='maintenance-daily';$lock=db()->query("SELECT GET_LOCK('gympro-maintenance',5) locked")->fetch_assoc()['locked']??0;if(!$lock){fwrite(STDERR,"Another maintenance run is active.\n");exit(1);}try{
 db_execute("INSERT INTO JOB_RUN (JobKey,LastStartedAt,LastStatus) VALUES (?,NOW(),'RUNNING') ON DUPLICATE KEY UPDATE LastStartedAt=NOW(),LastStatus='RUNNING'",'s',[$key]);
 $expired=db_all("SELECT UserID FROM USER_ACCOUNT WHERE Role='MEMBER' AND Status='PENDING_PAYMENT' AND PaymentDueAt<NOW()");foreach($expired as $row){db_execute("UPDATE USER_ACCOUNT SET Status='EXPIRED',ExpiredAt=COALESCE(ExpiredAt,NOW()) WHERE UserID=? AND Status='PENDING_PAYMENT'",'i',[$row['UserID']]);notify_users([(int)$row['UserID']],'Registration payment window expired','Sign in to choose a plan and restart your payment window.','WARNING');}
 db_execute("UPDATE SUBSCRIPTION SET Status='EXPIRED' WHERE Status='ACTIVE' AND EndsAt<NOW()");db_execute("UPDATE USER_ACCOUNT u JOIN SUBSCRIPTION s ON s.MemberID=u.MemberID SET u.Status='EXPIRED',u.ExpiredAt=COALESCE(u.ExpiredAt,NOW()) WHERE u.Role='MEMBER' AND u.Status='ACTIVE' AND s.Status='EXPIRED' AND NOT EXISTS (SELECT 1 FROM SUBSCRIPTION a WHERE a.MemberID=u.MemberID AND a.Status='ACTIVE' AND a.EndsAt>NOW())");
 $stale=db_all("SELECT u.UserID,u.MemberID,u.TrainerID,u.Email FROM USER_ACCOUNT u WHERE u.Status IN ('EXPIRED','REJECTED') AND COALESCE(u.ExpiredAt,u.RejectedAt)<DATE_SUB(NOW(),INTERVAL 30 DAY) AND u.AnonymizedAt IS NULL");foreach($stale as $u){transaction(function()use($u){$anon='anonymized-'.$u['UserID'].'@invalid.local';db_execute("UPDATE USER_ACCOUNT SET Email=?,PasswordHash='!',Status='ANONYMIZED',AnonymizedAt=NOW() WHERE UserID=?",'si',[$anon,$u['UserID']]);if($u['MemberID'])db_execute("UPDATE MEMBER SET Name='Anonymized Member',NIC=CONCAT('ANON-',MemberID),DOB=NULL,Gender=NULL,Email=NULL,Address=NULL,PhoneNo=NULL,ArchivedAt=NOW() WHERE MemberID=?",'i',[$u['MemberID']]);if($u['TrainerID']){foreach(db_all('SELECT StoredName FROM TRAINER_DOCUMENT WHERE TrainerID=?','i',[$u['TrainerID']]) as $d)@unlink(ROOT_PATH.'/storage/trainer-documents/'.$d['StoredName']);db_execute('DELETE FROM TRAINER_DOCUMENT WHERE TrainerID=?','i',[$u['TrainerID']]);db_execute("UPDATE TRAINER SET Name='Anonymized Trainer',PhoneNo=NULL,Email=NULL,Bio=NULL,ArchivedAt=NOW() WHERE TrainerID=?",'i',[$u['TrainerID']]);}});}
 db_execute("DELETE FROM EMAIL_VERIFICATION_TOKEN WHERE ExpiresAt<DATE_SUB(NOW(),INTERVAL 7 DAY)");db_execute("DELETE FROM PASSWORD_RESET_TOKEN WHERE ExpiresAt<DATE_SUB(NOW(),INTERVAL 7 DAY)");
 db_execute("UPDATE JOB_RUN SET LastCompletedAt=NOW(),LastStatus='SUCCESS',LastMessage=? WHERE JobKey=?",'ss',['Expired '.count($expired).' accounts; anonymized '.count($stale),$key]);echo "Expired ".count($expired)." account(s); anonymized ".count($stale)." record(s).\n";
}catch(Throwable $e){db_execute("UPDATE JOB_RUN SET LastCompletedAt=NOW(),LastStatus='FAILED',LastMessage=? WHERE JobKey=?",'ss',[$e->getMessage(),$key]);fwrite(STDERR,$e->getMessage()."\n");exit(1);}finally{db()->query("SELECT RELEASE_LOCK('gympro-maintenance')");}
