<?php
require_once __DIR__.'/../bootstrap/app.php';use GymPro\Services\SubscriptionService;require_role('MEMBER');$u=current_user();$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$id=SubscriptionService::choosePlan((int)$u['MemberID'],(int)($_POST['plan_id']??0),(int)$u['UserID']);redirect('member/checkout.php?subscription_id='.$id);}catch(Throwable $e){$errors[]=$e->getMessage();}}
$plans=db_all('SELECT * FROM MEMBERSHIP_PLAN WHERE IsActive=1 ORDER BY Price');$current=db_one('SELECT s.*,p.AllowsGymAccess,p.AllowsClasses FROM SUBSCRIPTION s JOIN MEMBERSHIP_PLAN p ON p.PlanID=s.PlanID WHERE s.MemberID=? ORDER BY s.SubscriptionID DESC LIMIT 1','i',[$u['MemberID']]);
$pageTitle='Membership';$pageSubtitle='Plans and subscription status';include ROOT_PATH.'/includes/header.php';?>
<?php if($errors):?><div class="alert alert-danger" role="alert"><?=e(implode(' ',$errors))?></div><?php endif;?>
<?php if($current):?><div class="callout"><div><strong><?=e($current['PlanNameSnapshot'])?> — <?=e($current['Status'])?></strong><p><?= $current['EndsAt']?'Valid until '.e(date('d M Y',strtotime($current['EndsAt']))):'Payment required'?></p></div><?php if($current['Status']==='PENDING_PAYMENT'):?><a class="btn btn-primary" href="checkout.php?subscription_id=<?=$current['SubscriptionID']?>">Continue checkout</a><?php endif;?></div><?php endif;?>
<div class="plan-grid"><?php foreach($plans as $p):?><article class="plan-card"><span class="badge <?=$p['AllowsClasses']?'badge-blue':'badge-grey'?>"><?=$p['AllowsClasses']?'Classes included':'Gym plan'?></span><h2><?=e($p['PlanName'])?></h2><p><?=e($p['PlanDetails'])?></p><div class="plan-price">Rs.<?=number_format((float)$p['Price'],2)?></div><small><?=e($p['Duration'])?> month cycle · Gym: <?=$p['AllowsGymAccess']?'Yes':'No'?> · Classes: <?=$p['AllowsClasses']?'Yes':'No'?></small><form method="post"><?=csrf_field()?><input type="hidden" name="plan_id" value="<?=$p['PlanID']?>"><button class="btn btn-primary" type="submit">Select plan</button></form></article><?php endforeach;?></div>
<?php include ROOT_PATH.'/includes/footer.php';?>
