<?php
require_once __DIR__.'/../bootstrap/app.php';require_role('MEMBER');$u=current_user();
$member=db_one('SELECT m.*,s.Status SubscriptionStatus,s.EndsAt,p.PlanName FROM MEMBER m LEFT JOIN SUBSCRIPTION s ON s.SubscriptionID=(SELECT s2.SubscriptionID FROM SUBSCRIPTION s2 WHERE s2.MemberID=m.MemberID ORDER BY s2.SubscriptionID DESC LIMIT 1) LEFT JOIN MEMBERSHIP_PLAN p ON p.PlanID=s.PlanID WHERE m.MemberID=?','i',[$u['MemberID']]);
$classes=db_all("SELECT c.ClassName,c.DateOfClass,c.StartTime,e.Status FROM ENROLLMENT e JOIN CLASS c ON c.ClassID=e.ClassID WHERE e.MemberID=? AND e.Status IN ('PENDING','ENROLLED') ORDER BY c.DateOfClass LIMIT 5",'i',[$u['MemberID']]);
$pageTitle='Member dashboard';$pageSubtitle='Your membership, classes, and updates';include ROOT_PATH.'/includes/header.php';?>
<div class="stats-grid"><div class="stat-card stat-blue"><div class="stat-label">Account</div><div class="stat-value value-small"><?=e(str_replace('_',' ',$u['Status']))?></div><div class="stat-sub"><?=e($member['MemberNumber']??'')?></div></div><div class="stat-card stat-green"><div class="stat-label">Membership</div><div class="stat-value value-small"><?=e($member['SubscriptionStatus']??'Not selected')?></div><div class="stat-sub"><?=e($member['PlanName']??'Choose a plan')?></div></div><div class="stat-card stat-amber"><div class="stat-label">Ends</div><div class="stat-value value-small"><?=e($member['EndsAt']?date('d M Y',strtotime($member['EndsAt'])):'—')?></div><div class="stat-sub"><?=count($classes)?> current class request(s)</div></div></div>
<?php if(in_array($u['Status'],['PENDING_PAYMENT','EXPIRED'],true)):?><div class="callout"><div><strong>Activate your membership</strong><p>Select a plan and complete the simulated card checkout.</p></div><a class="btn btn-primary" href="membership.php">Choose plan</a></div><?php endif;?>
<div class="dash-card"><div class="dash-card-title">Current classes</div><ul class="dash-list"><?php if(!$classes):?><li><span class="meta">No active class requests.</span></li><?php endif;foreach($classes as $c):?><li><span class="name"><?=e($c['ClassName'])?></span><span class="meta"><?=e($c['DateOfClass'])?> · <?=e(substr($c['StartTime'],0,5))?> · <?=e($c['Status'])?></span></li><?php endforeach;?></ul></div>
<?php include ROOT_PATH.'/includes/footer.php';?>
